version: '2'
services:
  elastictwo:
    image: elasticsearch:2-alpine
  elasticfive:
    image: elasticsearch:5-alpine
  testtwo:
    build: .
    command: bundle exec rake
    environment:
      ELASTICSEARCH_URL: 'elastictwo:9200'
    volumes:
      - .:/stretchy
    links:
      - elastictwo
  testfive:
    build: .
    command: bundle exec rake
    environment:
      ELASTICSEARCH_URL: 'elasticfive:9200'
    volumes:
      - .:/stretchy
    links:
      - elastictwo
